### ISSUE TITLE
createBunHttpHandler is forcing me to full ALL parameters

### ISSUE THREAD

**Issue by buzzy** [cah4a/trpc-bun-adapter#8] opened 2024-08-01 23:26 UTC
![image](https://github.com/user-attachments/assets/90e3656c-ac97-485e-998d-b44765cf7132)

**Comment by cah4a** [comment] 2024-08-07 08:06
Hey @buzzy,

Looks like it's a duplicate of #7.
Please upgrade package to version 1.1.2

**Closed by cah4a** 2024-08-07 08:06 UTC
